service: email-sniffer-api

package:
  individually: true

plugins:
  - serverless-bundle
  - serverless-offline
  - serverless-dotenv-plugin

provider:
  name: aws
  runtime: nodejs12.x
  stage: prod
  region: eu-west-1
  environment:
    MAX_DEPTH: 3

functions:
  sniffer:
    handler: functions/sniffer.handler
    events:
      - http:
          path: sniffer
          cors: true
          method: get
